//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTNX_Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job_Seeker_Questionnaire
    {
        public int Id { get; set; }
        public byte Experience { get; set; }
        public string Industries { get; set; }
        public string Locations { get; set; }
        public string Keywords { get; set; }
    }
}
